### ISSUE TITLE
Take some ideas from floorp browser and Ghostery and Basilisk browser and ice raven to reduce data and adjusting performance settings to reduce ram, 

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Mercury#1]
I discover Mercury browser with pleasure !

but I don't see a link to download it ?

I hope that Mr Alex will make changes to reduce the data used by the session store and session restores, there are a lot of parameters relating to the session store parameter that I no longer know for sure which parameter to disable unfortunately :(
   I also hope there will be an option to disable MSE media source extension quickly so we can buffer full video in youtube and some streaming site, pale moon browser has option to disable media source extension, and may be Mercury can be inspired by Basilisk browser which has recently been updated and the project relaunched:

https://www.basilisk-browser.org/

or the amazing Floorp browser make by japeneese students community, this is new updates adress !
 
https://floorp.app/
https://github.com/Floorp-Projects/Floorp

and ice raven browser : 

https://github.com/fork-maintainers/iceraven-browser
and also to enable quickly D3D9 beacause i because I tested this setting on chromium and the browser becomes fast, as well as an option to disable javascript by default to avoid malware, and option for adjusting performance settings to reduce memory can be done in Preferences or by changing the dom.ipc .processCount value to 1-8 and browser.preferences.defaultPerformanceSettings.enabled to false manually in about:config.

However you may want to manually adjust this setting to increase performance even further or decrease memory usage on low-end devices.

https://wiki.archlinux.org/title/Firefox/Tweaks#Change_Performance_settings

and also disbale prefetch and captive portal ! 

thank you very much !
 

and Ghostery
https://github.com/ghostery/user-agent-desktop
https://www.ghostery.com/

"Firefox and Chrome have been found to continuously write so much data that it might affect the durability of SSDs. Both browsers write an incredible amount of data to disk, even when idle.

firefox-with-32gb-written-in-a-single-day", this was in 2016

**Comment by Alex313031** [comment]
@gz83 Im taking some themeing from Floorp, and taking some patches from Ghostery.
