### ISSUE TITLE
package update pulling 121.0.2

### ISSUE THREAD

**Issue by Midnight1938** [Alex313031/Mercury#102]
I am running Arch, and pulling mercury package with yay. Which is trying to pull version 121.0.2, which is a windows release

**Comment by Alex313031** [comment]
@Midnight1938 The maintainer needs to update the aur pkgbuild so that it fetches only linux releases. This repo initially only hosted Linux builds, so thats probably why. If you can send me the AUR page, or send me the contact info or github of the maintainer, I can work with them to fix this.

**Comment by Midnight1938** [comment]
> @Midnight1938 The maintainer needs to update the aur pkgbuild so that it fetches only linux releases. This repo initially only hosted Linux builds, so thats probably why. If you can send me the AUR page, or send me the contact info or github of the maintainer, I can work with them to fix this.

Yes, following is [the page](https://aur.archlinux.org/packages/mercury-browser-bin) by xiota
