### ISSUE TITLE
PDFs don't open properly

### ISSUE THREAD

**Issue by Korygauger** [Alex313031/Mercury#105]
PDF's when launched from outside mercury don't open and instead open up three tabs of errors. PDFs open normally with drag and drop though.

OS: Linux mint
File browser: tried 3 all three produced this error krusader, ranger, and whatever kde comes with.

just did some sleuthing it looks like it isn't grabbing the whole file path and stops at spaces.
![3_001](https://github.com/Alex313031/Mercury/assets/58522673/0831f1c1-8286-40af-a13f-c3d9ab4dd749)

**Comment by Alex313031** [comment]
@Korygauger Perhaps I need to add it as a file handler in the .dekstop file and the debian SCHEMA file.

**Comment by kovalensky** [comment]
@Alex313031 Some pdfs are not visible, it's really annoying when you have to use other tools to view them.
**[Example](https://archive.org/download/in.ernet.dli.2015.174934/2015.174934.Orientations_text.pdf)**
