### ISSUE TITLE
Reopen issue "SSD will die prematurely when watching youtube video" because github censor the issue 

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Mercury#106]
Hello Mr @Alex313031 and Mr @gz83 , what do you think about this worrying phenomenon that can kill our ssd and hhd ?

I think Mercury Browser, after verification tests, should enable this necessary setting by default described and explained by Mr @kssfilo to save the users hard drive, thank you !

If you continue to watch Youtube in Firefox, SSD will die prematurely and how to deal with it :

https://kanasys.com/tech/892

@DumbledoreCalrissian 

This is a very old issue (I think it was popular in 2016 and 2017), but this is simply not a real thing. You can refer to several posts between now and 2017 to see Firefox doesn't kill SSDs.

@mestirmestir

@DumbledoreCalrissian We hope so ! we are waiting confirmation from @kssfilo @Alex313031 @gz83

@mestirmestir
Author

@DumbledoreCalrissian Hello, Do you have a logical explanation why Firefox currently has a cache greater than 1Gb while in other browsers, this cache does not exceed 225 MB? I fear that Firefox uses the cache for the video cache

**Comment by Alex313031** [comment]
@trimechee If anything, Chromium caches more on SSDs. But I wouldn't worry too much about it.

**Comment by trimechee** [comment]
Thank yu Mr @Alex313031 for these infrmations :) We are waiting for Mr.'s response, because there is no publication date for the article that I posted so we do not know if it is talking about old or recent fiefox..... It's up to you to see if it is appropriate to leave the issue open or close it, perhaps after a verification test if it is a deprecated bug, i.e. this bug has been corrected by a recent version of the browser...

Personaly I have an old HDD which is 7 years old and has been used a lot, it doesn't bother me that Firefox uses 1.1 Gb of cache because it helps avoid fragmentation of my hard drive and I'm even surprised that edge, chromium , chrome....only use between 225MB and 350MB of disk cache....but what can be annoying we can see 3 hour documentaries on YouTube and if YouTube caches a 1080p video, the hdd or ssd may be.....
