### ISSUE TITLE
Feature Request: Private Browsing w/ TOR

### ISSUE THREAD

**Issue by Chaython** [Alex313031/Mercury#113]
One of my favorite features of Brave browser, is you can browse with TOR giving an actual private browsing experience vs incognito/privatebrowsing which only removes cookies...

**Comment by superuser-miguel** [comment]
@Chaython Use Tor. . .

**Comment by Chaython** [comment]
> @Chaython Use Tor. . .

Much more convenient to ctrl shift n
Also allowing consistency in browser extensions etc
