### ISSUE TITLE
[Request] Any beautiful soul willing to maintain Mercury on Chocolatey?

### ISSUE THREAD

**Issue by UnholySheep** [Alex313031/Mercury#117]
I'm loving this browser, Alex has done an amazing job and I know Thorium has its priority over this one, that's why you can already find it on Chocolatey to easily update, so I'm asking for someone to maintain Mercury as well, it would be amazing to update without the hassle of external scripts or checking the releases every once in a while. I would do it myself, unfortunately I have 0 experience on this kind of stuff and I doubt I could do a nice job.

**Comment by TheCakeIsNaOH** [comment]
@UnholySheep Package created here: https://community.chocolatey.org/packages/mercury
