### ISSUE TITLE
Wrong inactive tab text and context menu colors in dark mode

### ISSUE THREAD

**Issue by brian6932** [Alex313031/Mercury#12]
![image](https://user-images.githubusercontent.com/18603393/229244960-0a770afc-3d9c-4d2e-95ad-58d97ec8c3ab.png)
![image](https://user-images.githubusercontent.com/18603393/229245497-d47b8585-daa5-4b76-8337-36b12b7b765b.png)

**Comment by Alex313031** [comment]
@brian6932 I've noticed multiple dark mode coloring issues with mercury, with every build I've made since I started the project.

It only happens on windows. I am not sure what causes it. I will investigate to see if it is my source code, or the mozconfig.

**Comment by Alex313031** [comment]
@brian6932 @ftphikari Fixed! Releases coming soon, based on firefox 115ESR

**Comment by Alex313031** [comment]
@brian6932 @ftphikari Fixed! See latest release > https://github.com/Alex313031/Mercury/releases/tag/v.115.0.0

**Comment by ftphikari** [comment]
Can confirm, it's fixed
