### ISSUE TITLE
[Feature Request] x86-64-v4 / AVX512 support

### ISSUE THREAD

**Issue by d3-X-t3r** [Alex313031/Mercury#121]
From what I understand, Mercury only supports x86-64-v3.

Are there any plans to provide an x86-64-v4 (AVX512) optimized package?

**Comment by Alex313031** [comment]
@d3-X-t3r Mercury supports SSE3, SSE4, AVX, and AVX2.

One could modify https://github.com/Alex313031/Mercury/blob/main/mozconfigs/mozconfig-win-avx2 and replace x86-64-v3 with x86-64-v4
