### ISSUE TITLE
Add a Github Action to build and post the release.

### ISSUE THREAD

**Issue by SashaXser** [Alex313031/Mercury#122]
Why not just make a Github Action that will automatically build and update the Mercury version? 
Also in this way in releases can maintain the relevance of dependencies, for example, in the most recent posted build, the build was made on Rust 1.70, which is already at least half a year old.

**Comment by gz83** [comment]
I personally do not recommend using this feature under the current circumstances, and we may also adjust the code before compiling the browser or during the process of compiling the browser.

**Comment by SashaXser** [comment]
> I personally do not recommend using this feature under the current circumstances, and we may also adjust the code before compiling the browser or during the process of compiling the browser.

Almost all Firefox forks use it, it's very handy and easy to use. I don't think anyone needs to change the code when compiling the browser.
