### ISSUE TITLE
Cross Building Windows AVX2 on Linux

### ISSUE THREAD

**Issue by wagesj45** [Alex313031/Mercury#125]
I'm attempting to set up an automated build process on a Debian Linux server. Having cloned the Mercury source, I followed all the steps in the [`BUILDING.md`](https://github.com/Alex313031/Mercury/blob/1bc3a84268440fbfd303bada55b3268bf797ffc4/docs/BUILDING.md) documents for the `--release` trunk and `--cross` setup value. This build process completes and runs fine on Windows.

What I'm struggling to do is convert the `mozconfig` values from `mozconfigs/mozconfig-win-avx2`. Specifically, I'd like to enable `AVX2` support and target the `znver3` or `x86-64-v3` architecture. A few things I've noticed:

* `AVX` is enabled, not `AVX2`
* There is a hard-coded value for `WIN32_REDIST_DIR`, that looks like we are assuming we're building on Windows using the MozillaBuild console (/c/... directory structure).
* `-mavx -maes` is used instead of `-march=x86-64-v3`
* Probably a lot of subtle things I'm missing.

Is there now, or could there be, a setup value that can specify march value and `AVX` support? And is there a requirement for these specifications (`AVX2`, `march=x86-64-v3`) that require the Microsoft C++ compiler specified in `WIN32_REDIST_DIR`? Is there a method I could use to translate the values from `mozconfig-win-avx2` to `mozconfig-win-cross`?

**Comment by Alex313031** [comment]
@wagesj45 Here you go! > https://github.com/Alex313031/Mercury/commit/5f762574700e542480eb375d01e9d643cc6ba011

**Comment by wagesj45** [comment]
Preliminary testing gave me an executable, but packaging the installer failed. I'm going to try again on a fresh Ubuntu Server installation, since that distro is suggested by the official Firefox documentation. I really appreciate the help, though! Will update when I figure out more.

**Comment by wagesj45** [comment]
So for future reference, this config does indeed work. I switched to a fresh install of Ubuntu Server and was able to install all dependencies and build successfully. I really appreciate your help!
