### ISSUE TITLE
122.0.2 SSE3 linux archives contain wrong binary 

### ISSUE THREAD

**Issue by xiota** [Alex313031/Mercury#126]
Both `deb` and `zip` are affected.  The 122.0.2 SSE3 linux archives contain the wrong binary.
```
$ readelf -a mercury | grep Machine
  Machine:                           AArch64
```

**Comment by Alex313031** [comment]
OMFL did i make an upload mistake AGAIN.

**Comment by Alex313031** [comment]
@xiota Looks like not only did I make that mistake, but the arm ones are correct. Means I need to rebuild the SSE3 version as I didn't keep the binaries.

**Comment by Alex313031** [comment]
@xiota What I mean is I thought this was like last time, where I accidentally switched two. But its ok, it will only take an hour. How did you discover this? Do you always use the SSE3 releases. Or are you keeping my ass in check by checking the binaries in all the releases every time? (LOL not a bad idea, considering I have also done this in the thorium repo)

**Comment by xiota** [comment]
I am the current maintainer of some `thorium-browser-*` and `mercury-browser-*` packages on AUR.  They attempt to automatically package the latest release.  When filename patterns change, the update mechanism breaks.  I found the problems while updating the packages.

I am retiring the `-sse3-bin` packages and switching the `-bin` packages to the SSE3 variants.

* Too many versions.  Easy to make mistakes by mixing up small differences.
* Someone requested the AVX2 Thorium, but benchmarking showed no performance difference among the different variants.
* Main benefit of Thorium that I've seen is short startup times.  All versions of Thorium seem to startup equally quickly.
* Examination of Chromium binaries, Thorium variants, Firefox forks, and Mercury variants reveals AVX and AVX2 instructions are present in all builds.  Checking processor capabilities during runtime seems to be standard practice among Firefox and Chromium browsers.  Targeting different instruction sets would not be expected to significantly improve performance.
* From benchmarking different browsers and forks:
    * Forks cluster around the parent browser.  Newer releases perform better.  So, a fork of Firefox would be expected to perform better than a fork of Firefox ESR, assuming similar build parameters (mainly PGO).
    * PGO significantly improves performance.  A fork of Firefox ESR built with PGO has the potential to perform similarly to a fork of Firefox built without PGO.
