### ISSUE TITLE
Speedometer Performance Regression

### ISSUE THREAD

**Issue by gianni-rosato** [Alex313031/Mercury#13]
Hello, I am experiencing bad Speedometer performance compared to standard Firefox on the latest Mercury 111 from the AUR.

![Mercury](https://take-me-to.space/kuQMl3F.webp)
![Firefox](https://take-me-to.space/VIMcA6t.webp)

`➜  ~ inxi -v
CPU: 16-core (8-mt/8-st) 13th Gen Intel Core i7-13700K (-MST AMCP-)
speed/min/max: 1450/800/5400 MHz Kernel: 6.2.8-zen1-1-zen x86_64 Up: 17m
Mem: 4548.1/31868.8 MiB (14.3%) Storage: 6.83 TiB (22.7% used) Procs: 499
Shell: Zsh inxi: 3.3.26`

[Troubleshooting Information (about:support)](https://github.com/Alex313031/Mercury/files/11127674/Troubleshooting.Information.zip)

Let me know if you need any more information. Thank you!

**Comment by Alex313031** [comment]
@gianni-rosato Hmmmm. That interesting, because this release is based on stable firefox, just with compiler optimizations, so it should be *more* performant, not less.

**Comment by gianni-rosato** [comment]
Is there a particular compiler flag that could change this? Should I try building from source?

**Comment by BlueSwordM** [comment]
Very weird, but I'm getting the same speedometer numbers as you do, with a much weaker CPU (3700X).

**Comment by gianni-rosato** [comment]
Blue also told me they tested various other benchmarks & didn't observe any differences. @Alex313031, can you try to replicate what we're seeing here?

**Comment by sandboiii** [comment]
Tested the newest v.112.0.3 build on my laptop. Seems to be much better.
Firefox - 129
Mercury - 135

**Comment by sandboiii** [comment]
v115.0.0
Firefox - 136
Mercury - 157

EmberJS tests seem to be slow, looks like on Firefox they pass faster

**Comment by sandboiii** [comment]
v115.3.0
Firefox - 153
Mercury - 159

Looks like they are almost the same speed. I guess this issue can be closed now

**Comment by afonsofrancof** [comment]
Having the same issue.
Firefox 118.0.2
Mercury 115,4,0
Windows 10
![image](https://github.com/Alex313031/Mercury/assets/56155712/ff571254-68c8-4850-bc1e-0976f01d9665)

**Comment by gz83** [comment]
There are differences between different versions and systems, and the performance test is for reference only. In addition, the best test is to compare versions with the same version number.
