### ISSUE TITLE
Build Fails Due to Missing distutils.spawn Module on Python 3.12

### ISSUE THREAD

**Issue by Fiffian** [Alex313031/Mercury#130]
## Environment
- OS: Nobara 39
- Python Version: 3.12
- Mercury Browser Version: v.122.0.2

## Description
I encountered a build error when attempting to compile the Mercury browser on Fedora using Python 3.12. The error indicates that the `distutils.spawn` module is missing, which is expected since `distutils` has been deprecated and is removed in Python 3.12.

Here is the error output:
![image](https://github.com/Alex313031/Mercury/assets/36559549/68e4935a-9c73-4471-89c6-b1f4232cb231)

**Comment by gz83** [comment]
Please install an old version of python and compile in an old version of python virtual environment.  In addition, it is recommended to use the appropriate environment listed by Firefox for compilation.
