### ISSUE TITLE
Can't download files from Google Drive.

### ISSUE THREAD

**Issue by Cunpa** [Alex313031/Mercury#14]
When I right click files in a google drive folder, nothing happens and they don't download. I'm using the latest version of Mercury with extensions disabled. The same issue occurs whether I'm signed into Google or not. I didn't change any of the cookie settings, and have it set to 'Standard'.
![Screenshot (3680)](https://user-images.githubusercontent.com/28813330/230272526-c08b83c0-cd1b-4510-a0ea-6405bdda5b74.png)

**Comment by Cunpa** [comment]
I just fixed this by setting my User Agent to Google Chrome.

**Comment by Cunpa** [comment]
YouTube Live chat doesn't work either, but changing my User Agent fixed this too.

![Screenshot (3687)](https://user-images.githubusercontent.com/28813330/231844605-51d21e24-1767-47bf-8d08-c03af8b186a9.png)

**Comment by jobbautista9** [comment]
`general.useragent.compatMode.firefox` should be enabled by default so that Mercury won't run into webcompat issues like this.

**Comment by Alex313031** [comment]
@Cunpa @jobbautista9 Fixed!

**Comment by Alex313031** [comment]
@Cunpa @jobbautista9 Fixed! See latest release > https://github.com/Alex313031/Mercury/releases/tag/v.115.0.0
