### ISSUE TITLE
html files crash the tab

### ISSUE THREAD

**Issue by LoopyLoot** [Alex313031/Mercury#141]
When I try to open html files the tab crashes, is there any change I can make in about:config to avoid this? ty

![Screenshot 2024-02-21 015838](https://github.com/Alex313031/Mercury/assets/74234524/b2d09c3b-7381-4d87-8509-38eedbd9361b)

**Comment by JoccE0** [comment]
I have the same issue but cant figure it out why, it works in FF and Chromium without issues
