### ISSUE TITLE
Will you provide PGO optimized builds?

### ISSUE THREAD

**Issue by iahung3** [Alex313031/Mercury#147]
Like this:

https://sourceforge.net/projects/libportable/files/Iceweasel/Stable/123.x/x86_64/Iceweasel-v123.0.en_US_win64_clang_pgo.7z/download

**Comment by gz83** [comment]
The browser has been optimized to the best of our ability

**Comment by iahung3** [comment]
> The browser has been optimized to the best of our ability

Profile Guided Optimization is something completely different from x86_64-v3 or AVX2.

**Comment by gz83** [comment]
Compiling with pgo will prevent us from using more specific compilation parameters in the current situation (such as parameters that need to be passed to generate the installation package, etc.)

**Comment by Alex313031** [comment]
@gz83 @iahung3 No, Mercury has been compiled with PGO since ver. 119. @gz83 Been using PGO on all platforms, even Windows and MacOS now.

So yeah, they have PGO.

**Comment by gz83** [comment]
> @gz83 @iahung3 No, Mercury has been compiled with PGO since ver. 119. @gz83 Been using PGO on all platforms, even Windows and MacOS now.
> 
> So yeah, they have PGO.

OK

**Comment by K4sum1** [comment]
Seeing as resolved, maybe close the issue?

Kinda related idk @Alex313031 I would really like to ask you about the new performance stuff you did for 123.0.1, can you hop on Discord?
