### ISSUE TITLE
Provide nixpkg for both Thorium and Mercury & SSE3/AVX2 builds for Mercury

### ISSUE THREAD

**Issue by legovo** [Alex313031/Mercury#15]
Nixpkgs package manager & build system enables static linking for almost everything, while (as I know) generally more features work compared to Snap/Flatpak. Nixpkg application can work on any distro for a given architecture. Same goes for Thorium, I would like to see a nixpkg for it as well.
I would also like to see SSE3 releases for Mercury.

**Comment by toprak** [comment]
I would like to see SSE3 for Mercury too!
