### ISSUE TITLE
Titlebar color

### ISSUE THREAD

**Issue by yZibi** [Alex313031/Mercury#16]
Mercury don't recognize windows theme & don't change titlebar accent color with dark theme.
First image - Firefox, second - Mercury.
![Snipaste_2023-04-09_12-31-25](https://user-images.githubusercontent.com/87340706/230765871-c65dbefd-6355-417d-bfb5-62b7501731a1.png)
![Snipaste_2023-04-09_12-33-05](https://user-images.githubusercontent.com/87340706/230765873-0ba241cc-23e0-422f-baef-cbbc724f6d7c.png)

**Comment by yZibi** [comment]
112.0.3 Still relevant.

**Comment by Alex313031** [comment]
@yZibi Fixed!

**Comment by Alex313031** [comment]
@yZibi Fixed! See latest release > https://github.com/Alex313031/Mercury/releases/tag/v.115.0.0
