### ISSUE TITLE
What windows version am I running?

### ISSUE THREAD

**Issue by bcookatpcsd** [Alex313031/Mercury#166]
As a windows (or linux) user.. how do you know which AVX, AVX2, SSE3, SSE4 I am running..

I'm a Ryzen7 cpu.. and understand that all will work.. 

![image](https://github.com/Alex313031/Mercury/assets/55087301/977b4848-9596-4850-a08d-f63f61650063)

I'm taking the cpu flags (in the order listed) as oldest to newest.. and AVX2 > ( AVX || SSE4 || SSE3 )

Other than, I know I downloaded the avx2 installer.. is there anyway to tell that this is the avx2 binary? 

![image](https://github.com/Alex313031/Mercury/assets/55087301/4a4f1e72-d7b9-4e9b-a4a2-91f0d3bf97d5)

![image](https://github.com/Alex313031/Mercury/assets/55087301/1f3146cd-d795-405d-b5c1-b8dde6c91fbc)

Thank you in advance..

**Comment by SashaXser** [comment]
> As a windows (or linux) user.. how do you know which AVX, AVX2, SSE3, SSE4 I am running..
> 
> I'm a Ryzen7 cpu.. and understand that all will work..
> 
> ![image](https://private-user-images.githubusercontent.com/55087301/317273428-977b4848-9596-4850-a08d-f63f61650063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTIxNTcsIm5iZiI6MTcxMTU1MTg1NywicGF0aCI6Ii81NTA4NzMwMS8zMTcyNzM0MjgtOTc3YjQ4NDgtOTU5Ni00ODUwLWEwOGQtZjYzZjYxNjUwMDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE1MDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMDZhZDZiMjZjMGNmNTc3NDBlNDA1YzUxMzJlMzY5OTY2MWU3ZTdkYzkyNWRlOGQ2OTJlYjc4YTFmNTA2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kh4RWF6hhng5v72Vr9ic9tl6C_zdPdJekdcPRxCuQrg)
> 
> I'm taking the cpu flags (in the order listed) as oldest to newest.. and AVX2 > ( AVX || SSE4 || SSE3 )
> 
> Other than, I know I downloaded the avx2 installer.. is there anyway to tell that this is the avx2 binary?
> 
> ![image](https://private-user-images.githubusercontent.com/55087301/317274259-4a4f1e72-d7b9-4e9b-a4a2-91f0d3bf97d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTIxNTcsIm5iZiI6MTcxMTU1MTg1NywicGF0aCI6Ii81NTA4NzMwMS8zMTcyNzQyNTktNGE0ZjFlNzItZDdiOS00ZTliLWE0YTItOTFmMGQzYmY5N2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE1MDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZGUzNmJhYWI1NmUyNjk1NWMwNmQ3MWNkYTA3YzIxZWE5M2UxY2RiZDU4ZGE1YWE2ZDA0MGZlZmJlZTU5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x_C4iM-5Bju9XFaEjQ0e_wTWshl8I8D1a2L-STLkf7M)
> 
> ![image](https://private-user-images.githubusercontent.com/55087301/317274763-1f3146cd-d795-405d-b5c1-b8dde6c91fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTIxNTcsIm5iZiI6MTcxMTU1MTg1NywicGF0aCI6Ii81NTA4NzMwMS8zMTcyNzQ3NjMtMWYzMTQ2Y2QtZDc5NS00MDVkLWI1YzEtYjhkZGU2YzkxZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE1MDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2M1NjEzZDhhNDljNGRmYjY1YjdmY2I1NGVkOGQ4MGU5ODRiZjNkM2I5NGE3NDJjZjFiY2RjY2FiZTc3ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aYn4C7tixWOPw7adG45rywe9WdGIs5Rn1BCkzLG7oIk)
> 
> Thank you in advance..


[Try this,](https://github.com/pkgw/elfx86exts) I can't say for sure how accurate the program is, but it seems like it might help you figure it out. Mercury is not fully covered with optimization flags. The same mtune and tune-cpu are missing. The same Thorium is more covered with optimization flags.

Here is the output of the program on the AVX2 Mercury:
```MODE64 (ret)
AVX (vmovaps)
NOVLX (vmovaps)
CMOV (cmovl)
BMI2 (shlx)
BMI (andn)
AVX2 (vpbroadcastq)
SSE2 (pause)
SSE1 (xorps)
Instruction set extensions used: AVX, AVX2, BMI, BMI2, CMOV, MODE64, NOVLX, SSE1, SSE2
CPU Generation: Unknown
