### ISSUE TITLE
[Windows] Compositor don't recognize OS

### ISSUE THREAD

**Issue by yZibi** [Alex313031/Mercury#18]
System: Windows 10.
Left - Librewolf, Right - Mercury
![Snipaste_2023-04-12_23-53-44](https://user-images.githubusercontent.com/87340706/231583216-c3a5d7c5-8f26-425d-8fcd-a6e7c1e7f1f7.png)
P.S. Have issues with firefox sync. Am i only one?

**Comment by yZibi** [comment]
112.0.3 Still relevant.

**Comment by Alex313031** [comment]
@yZibi Fixed! Releases coming soon

**Comment by Alex313031** [comment]
@yZibi Fixed! See latest release > https://github.com/Alex313031/Mercury/releases/tag/v.115.0.0
