### ISSUE TITLE
Which version should I be updating with (if any)?

### ISSUE THREAD

**Issue by filtrd** [Alex313031/Mercury#180]
I installed _mercury-browser_121.0.1_amd64.deb_ but since then there has been no amd64 releases, excuse my ignorance but should I be updating or can I update with one of the other alternative .deb versions?

**Comment by BSoD38** [comment]
All deb packages are for amd64 (except the one with ARM64 in its name). You have to choose the package that has the most recent available instruction set for your CPU.
To get all available instruction sets on your CPU, enter `cat /proc/cpuinfo` and look at the `flags` section.

Here is the list of flags you're looking for:
- SSE3: ssse3
- SSE4: sse4_2
- AVX: avx
- AVX2: avx2

If the list of flags is too long, you can filter it with `grep -m 1`. For example, to check if your CPU supports AVX2, use `cat /proc/cpuinfo | grep -m 1 avx2`. If you see no output, it's not supported.

This list is ordered from oldest to most recent instruction set. For example, if you CPU supports SSE3, SSE4 and AVX, install the AVX package. Unless your computer is incredibly old, it should at the very least support SSE4.2. If your computer is fairly recent (2015 or more recent), there's a fair chance it supports AVX2.
