### ISSUE TITLE
Can't build browser

### ISSUE THREAD

**Issue by pog5** [Alex313031/Mercury#2]
Trying to build the browser fails with a vauge error.

**Comment by Alex313031** [comment]
@pog5 Try again now. I just rebased the whole repo. You should be able to follow the linux firefox guide (making sure to select option 2 "desktop" rather than "Artifact mode"

Then simply run `./trunk`, `./setup`, and `./build`. These scripts assume that both the mercury repo, and the firefox repo are both with their default names and locations, i.e. ~/Mercury-main and ~/mozilla-unified

**Comment by Alex313031** [comment]
@pog5 I also just made V.110.0.a1 releases for both linux and windows x64

**Comment by iamevilmonarch** [comment]
I am building mercury v115.1.0 in void linux and by following the instructions in mercury docs
I need to ask is what do you mean by firefox repo cause i have followed two methods 
1. i placed my firefox repo from /usr/lib/firefox/ to ~/mozilla-unified 
2. i downloaded source code from firefox and placed in ~/mozilla-unified
_by trying both ways it is giving the following error 

Script to Rebase/Sync Mozilla repo on Linux._

Rebasing/Syncing with mozilla-unified Mercurial repository...
./trunk.sh: line 40: hg: command not found

can you please look into this issue and guide me

**Comment by pog5** [comment]
> I am building mercury v115.1.0 in void linux and by following the instructions in mercury docs I need to ask is what do you mean by firefox repo cause i have followed two methods
> 
> 1. i placed my firefox repo from /usr/lib/firefox/ to ~/mozilla-unified
> 2. i downloaded source code from firefox and placed in ~/mozilla-unified
>    _by trying both ways it is giving the following error
> 
> Script to Rebase/Sync Mozilla repo on Linux._
> 
> Rebasing/Syncing with mozilla-unified Mercurial repository... ./trunk.sh: line 40: hg: command not found
> 
> can you please look into this issue and guide me

Issue not related, create a new issue

**Comment by pog5** [comment]
Original issue fixed
