### ISSUE TITLE
Use Global Privacy Control instead of Do Not Track

### ISSUE THREAD

**Issue by jobbautista9** [Alex313031/Mercury#20]
I noticed that DNT is being sent by default:

https://github.com/Alex313031/Mercury/blob/27462b5ba305d609aa870843da94cd3e118a4ddc/app/profile/firefox.js#L1522

I don't really prefer having such a header enabled by default (it should be left to the user IMHO), but if you want to send by default, you should use its successor GPC instead of DNT which is pretty much obsolete and useless.

The relevant pref is `privacy.globalprivacycontrol.enabled`

**Comment by Alex313031** [comment]
@jobbautista9 Done!

**Comment by jobbautista9** [comment]
Thanks!

`privacy.globalprivacycontrol.functionality.enabled` also needs to be enabled, forgot about that too. Otherwise sites using GPC wouldn't be able to detect your GPC signal. See https://global-privacy-control.glitch.me/ for a test reference.

**Comment by Alex313031** [comment]
@jobbautista9 OK
Fixed! See latest release > https://github.com/Alex313031/Mercury/releases/tag/v.115.0.0
