### ISSUE TITLE
Cannot play netflix with Mercury 124.01a [MacOS]

### ISSUE THREAD

**Issue by shuryanc** [Alex313031/Mercury#206]
Got E100 and 1044 when pressing Play button, then netflix would go into https://www.netflix.com/clearcookies.

**Comment by loken116** [comment]
I have the same issue! Even on the last build. AVX2 on Windows 11

**Comment by tigers-aye** [comment]
Fwiw, I haven't been able to get Netflix working on Thorium-Win ever since I started using Thorium earlier this year, including on all updates since. Ditto on Mercury.

**Comment by Alex313031** [comment]
@shuryanc @loken116 @tigers-aye All of y'all, see number 2 in the Thorium FAQ, which also applies to this: 

https://github.com/Alex313031/thorium/blob/main/docs/FAQ.md#2

**Comment by shuryanc** [comment]
Ok. Thanks Alex.
