### ISSUE TITLE
`v115.0.0` bins break tag versioning

### ISSUE THREAD

**Issue by brian6932** [Alex313031/Mercury#25]
https://github.com/Alex313031/Mercury/releases/tag/v.115.0.0
Version tags should be the same as the bin names, not doing this makes packaging break
Example:
`https://github.com/Alex313031/Mercury/releases/download/v.115.0.0/mercury-115.0.en-US.win64.zip`
Should be:
`https://github.com/Alex313031/Mercury/releases/download/v.115.0.0/mercury-115.0.0.en-US.win64.zip`

**Comment by Alex313031** [comment]
@brian6932 Ok thanks, will fix. Thjs is because for the first version of a major version, the binaries for some reason don't put .0.0 in the name, just .0 I will rename the releases.
