### ISSUE TITLE
Is it possible to distribute .msi instead of/along with .exe?

### ISSUE THREAD

**Issue by ftphikari** [Alex313031/Mercury#26]
I don't have a password on my Windows account, only pin (for better security), and Firefox/Mercury .exe installer shows this window:
![image](https://github.com/Alex313031/Mercury/assets/92269215/bb36de41-43e6-4ebc-a1a9-87c6619d77ed)
There is nothing I can do, since I cannot log into anywhere without a password. But Firefox .msi installer does not have this issue, so I use that. But there is no .msi installer for Mercury. Perhaps it would be nice to have.

**Comment by win98se** [comment]
There is an option “Current user”, maybe try to use that?

**Comment by win98se** [comment]
Just tested myself; Could not reproduce this problem on my side.

**Comment by ftphikari** [comment]
No need to reproduce it, you can just google for it. It happens to some Windows accounts.
