### ISSUE TITLE
https://web.whatsapp.com/ does not  work

### ISSUE THREAD

**Issue by structnull** [Alex313031/Mercury#28]
https://web.whatsapp.com/ doesn't work with this error on archlinux with the latest aur release.

![image](https://github.com/Alex313031/Mercury/assets/87846149/d250b0d5-11cd-4226-a041-ed67e5d9c4e5)

**Comment by toprak** [comment]
@gz83 can you look into it?

**Comment by gz83** [comment]
Does the same issue exist in Firefox?

@toprak @chiefdinkan

**Comment by toprak** [comment]
@gz83 I tried it with firefox 117, the problem is not appearing on it, guess its problem of mercury

**Comment by gz83** [comment]
No, you should use the same version of firefox as mercury for testing

@toprak

**Comment by toprak** [comment]
@gz83 yeah tried with ffx 115.0.3 (64-bit), it has no prob, guess its mercuries prob

**Comment by gz83** [comment]
Sorry, still not correct, you should use 115.2.0esr version to test

@toprak

**Comment by toprak** [comment]
115.2.0esr (64-bit)
![2023-09-06-173852_959x1039_scrot](https://github.com/Alex313031/Mercury/assets/43301560/413f0dc8-d5ec-47e1-a32b-70e49f8b6bf4)
@gz83

**Comment by gz83** [comment]
Does your Mercury have any custom configurations as well as 3rd party addons?

If it has, please make a save and try opening whatsapp again with fresh user data.

@toprak

**Comment by toprak** [comment]
@gz83 sorry for delayed answer, I installed fresh linux, and did fresh installation for mercury-browser did not touch anything nor installed anything, problem still appears on my end.
