### ISSUE TITLE
x86-64-v3 variant

### ISSUE THREAD

**Issue by niktss** [Alex313031/Mercury#31]
The way I understand it, Mercury currently targets x86-64-v2 + AVX. It would be cool to have a version targeting the full v3 list, which includes among other things AVX2.

**Comment by gz83** [comment]
Firefox's infrastructure seems to be weak, and the O3 optimizations used for the clang compiler can't be fully applied to all code, and we should be constantly tweaking our optimization parameters

@Frivolous2

**Comment by Alex313031** [comment]
@HeadPlug @gz83 Mercury 115 now applies O3 to most code, except some third party submodules that use different build systems. For example, firefox uses chromium's webrtc library, which of course uses Ninja and has its own BUILD.gn with its own compiler flags, which aren't picked up by the ones set in the mozconfig, so for those things, it will use whatever the author decided to use for non debug builds. For most things that means O2 and SSE2 or SSE3. However, the important stuff like the UI, the rendering engine, javascript compiler, and webassembly module are compiled with O3 and AVX.

Interestingly, compared to Thorium, AVX2 seems to provide a much higher performance uplift for Firefox. With Chromium, the performance difference between AVX and AVX2 is not that much. In fact, I wouldn't make AVX2 builds if the community hadn't requested it and I didn't have @gz83 to help me.

For firefox, AVX2 alone (compiling it with just AVX2, no PGO, and no O3) provides a nice uplift, and actually smaller binary size. It actually seems more worth it and makes more sense to make x86-64-v3 builds of Mercury.

**Comment by HeadPlug** [comment]
I would be a damn liar if I said I understood most of that last comment, but it's things like these that make me want to learn more about the lower level stuff. 😃

> In fact, I wouldn't make AVX2 builds if the community hadn't requested it and I didn't have @gz83 to help me.

You should do what you want as a developer!  We the FOSS community get cool free stuff for nothing in return, so it's hoped that at least you the devs are enjoying the process in itself. 😁😅  

If AVX2 Firefox/Chrome is something you want to do, go for it. But if you'd rather work on sth else, just do that instead; you owe us users nothing, so don't let a bunch of FOSS nerds dictate what you do in your free time 😇💪
