### ISSUE TITLE
How to convert to Portable

### ISSUE THREAD

**Issue by j0912H97** [Alex313031/Mercury#35]
I want to make Mercury Portable.
What should I do?

**Comment by gz83** [comment]
I don't know whether you are using Windows or Linux version. Here are two articles about making a portable version of Firefox on Windows. The language of the article is Simplified Chinese. If you cannot read Simplified Chinese, you can use a translator Read the content of the article

https://zhuanlan.zhihu.com/p/24620052

https://mrx.la/142

@j0912H97

**Comment by Alex313031** [comment]
@gz83 @j0912H97 I will put a portable .bat in the windows .zip of the next release.

**Comment by hingbong** [comment]
[adonais/libportable](https://github.com/adonais/libportable) 
There's a thing that is able to make Firefox portable.
