### ISSUE TITLE
Mercury goes without permit

### ISSUE THREAD

**Issue by Ygarr** [Alex313031/Mercury#4]
....to this resources in background:
content-signature-2.cdn.mozilla.net
detectportal.firefox.com
firefox.settings.services.mozilla.com
push.services.mozilla.com
location.services.mozilla.com
contile.services.mozilla.com
aus5.mozilla.org
ciscobinary.openh264.org
and so on

**Comment by Alex313031** [comment]
@Ygarr What do you mean without permit?

**Comment by Alex313031** [comment]
@Ygarr Mercury is in its early stages. It is little more than a rebranded, compiler optimized, and UI tweaked firefox. I have not added the privacy patches from librewolf yet that would mitigate these mozilla "phoning home" background network requests, but that is something I'm going to work on in the future.

**Comment by G2G2G2G** [comment]
Why do you use firefox instead of librewolf as the one you compiler optimize?

**Comment by Alex313031** [comment]
@G2G2G2G Because I wanted to build my own fork. And add stuff in as I see fit from other forks.
