### ISSUE TITLE
Mercury Benchmark data is not proper

### ISSUE THREAD

**Issue by xd003** [Alex313031/Mercury#47]
I was checking mercury's benchmark data to see how it fares against thorium but it seems the data mentioned on the website [here](https://thorium.rocks/mercury_performance) is exactly the same as mentioned in Thorium, maybe there is some mistake that i believe woud want to be addressed

**Comment by Alex313031** [comment]
@xd003 It is not the same as the Thorium one, if you look, the pictures on the left are of Mercury. However, I never completed this page, and what information is on there is very out of date. I wouldn't rely on it. Eventually I will update the page with fresh information.
