### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by entrider** [Alex313031/Mercury#49]
Is there a reason why Mercury is based on Firefox ESR? Are you planning to support current Firefox versions?

**Comment by sergeevabc** [comment]
Mercury 115.4.0 crashes at launch on Windows 7 x64, but Firefox ESR 115.3.1 works, so I also wonder what @Alex313031 is about to do.

**Comment by entrider** [comment]
Performance of ESR sucks, and beta and nightly versions can do better than stable.
https://www.phoronix.com/review/mercury-firefox-perf

**Comment by sergeevabc** [comment]
> Performance of ESR sucks...

Thing is, Firefox ESR 115 is the [last version][1] that launches on Windows 7/8, so beta and nightly versions are for those who decided to upgrade OS to 10/11, whereas ~15% of userbase chose not to, me included. Options for the latter are Waterfox G5.1.13, Pale Moon, and Supermium so far. Quite amusing that HTML/CSS/JS rendering now depends on what OS you have. Anyway, I'd appreciate a clear Mercury developer's statement whether the support of Windows 7 users is considered or not.

[1]: https://support.mozilla.org/en-US/kb/firefox-users-windows-7-8-and-81-moving-extended-support

**Comment by entrider** [comment]
Yes, but you can't avoid the inevitable:
>Mozilla will provide security updates for these users until September 2024. No security updates will be provided after that date.

I doubt that Waterfox and even Palemoon developers will continue to support 115 ESR after that date.

**Comment by sergeevabc** [comment]
@entrider, Palemoon, fortunately, is not tied to the schedule of Mozilla since its developers adapt changes, including security related ones, selectively, not along with the parent ESR core. Not sure about Waterfox's strategy. Point is, there are forks, such as Firefox-based Palemoon and Chromium-based Supermium, meant for the rest of us who do not move in lock-step with the of Silicon Valley hegemons forcing users to upgrade by means of fearmongering and planned obsolescence instead of innovations like it was before. And I wonder if Mercury is one of them, or just another speed-only toy.

**Comment by sergeevabc** [comment]
Dear @Alex313031, could you be so kind to roll out Mercury based on Firefox 115.3.1, just for once at least? I'm desperately looking for a faster browser for a year to come.

**Comment by zooool** [comment]
@Alex313031 seems to have abandoned the project, sadly.
@entrider @sergeevabc For now all I can do is recommend GNU Icecat for Windows. It is based on Firefox ESR and works on Windows versions lower than 10. Even though it's a privacy fork, it is quite bloated with a ton of privacy features. Hopefully a "slim" Firefox ESR privacy fork will pop up again somewhere soon.

Binaries are here: https://icecatbrowser.org/download/
Source code can be found on that page as well.

**Comment by sergeevabc** [comment]
@zooool, Floorp does not work on my end, however IceCat does.
Thank you for researching and mentioning the alternatives for Windows 7 users.

**Comment by spacedrone404** [comment]
> @zooool, Floorp does not work on my end, however IceCat does. Thank you for researching and mentioning the alternatives for Windows 7 users.

Floorp works in Win 7 x64 ESU.
As for new versions of Mercury, any news?

**Comment by sergeevabc** [comment]
> @spacedrone404, Floorp works in Win 7 x64 ESU.

Not on my end. Version 11.6.1 released on 2023-11-21 throws errors. The same errors I see when launch the latest LibreWolf (incompatible with Windows 7 anymore, alas).

![2023-1210-0858 floorp 11-6-1](https://github.com/Alex313031/Mercury/assets/373718/d5fad309-44e5-47fc-a8e0-e1f6e34a9399) ![2023-1210-0903 floorp 11-6-1](https://github.com/Alex313031/Mercury/assets/373718/83fc0d6b-6fe8-4d49-bd3a-40a85f59627d)

**Comment by spacedrone404** [comment]
> my processor only supports SSE3.
Sorry to hear. 
i'm on top end Broadwell. This gen supports sse4.1/avx and currently dirt-cheap.

**Comment by sergeevabc** [comment]
@spacedrone404, well, I chose not to support environmental pollution by regularly replacing working hardware just to feed corporations and feel at the top of progress. Moreover, replacing a processor is not always easy no matter the price: if it is a desktop computer, you most likely need to replace a mother card and buy a compatible memory as well, and if it is a beloved laptop (my case) then replacement options are quite limited if any. So my current FF-based choice is IceCat then. However, I [informed](https://github.com/Floorp-Projects/Floorp/issues/623) Floorp devs.

**Comment by andika207** [comment]
> Floorp works in Win 7 x64 ESU.

I have just downloaded the portable and x64 version but neither of them works here.
I get the same error prompt as mentioned before @sergeevabc  similar to when installing Waterfox.
this AMD CPU only supports SSE4A instructions but my other intel CPU's would probably work.

**Comment by andika207** [comment]
> Floorp does not work on my end, however IceCat does. 
Thank you for researching and mentioning the alternatives for Windows 7 users.

Librewolf got stuck on version 115 too.
Firefox could have a larger user base if they were not stupid idiots because they could perfectly support Win7 and WinXP users
all this said I'm not worried because Supermium works perfect and is a significantly faster than all of the Firefox based crap.

**Comment by andika207** [comment]
>Moreover, replacing a processor is not always easy no matter the price

older hardware is often more expensive than the newer one, I'm looking up hardware for another WinXP rig so I can't pick anything too new due to the lack of drivers support.

**Comment by spacedrone404** [comment]
> Also I [informed](https://github.com/Floorp-Projects/Floorp/issues/623) Floorp devs.

As you may already know, they refused to do anything, at least at this point.

**Comment by Alex313031** [comment]
@sergeevabc @andika207 @spacedrone404 @entrider @zooool I have not abandoned any of my projects or Windows 7.

Making new builds soon as well as an explanation of where I was in the thorium repo.

The reason it is based on ESR is for win7 support.
I might either make seperate repos for mercury esr and mercury tip of tree, OR i might keep it at ESR 115 until the end of support in 2024.

**Comment by sergeevabc** [comment]
@Alex313031, Mercury v.115.4.0 does not work under Windows 7 x64 on my end because you compiled it with SSE4.1 as a strict requirement, whereas my Core 2 Duo supports SSE3 only. Please, do something about it, it's just a matter of setting a proper compilation switch.

**Comment by sergeevabc** [comment]
@Alex313031, Mercury v.115.4.0 does not work under Windows 7 x64 on my end.

![2023-1230-0523 mercury 115-4 bug 01](https://github.com/Alex313031/Mercury/assets/373718/54d422fd-8f57-4006-90da-899ddb184667)
![2023-1230-0523 mercury 115-4 bug 02](https://github.com/Alex313031/Mercury/assets/373718/c2e7a814-070d-49b4-8914-553a127023f1)

**Comment by Alex313031** [comment]
@sergeevabc @andika207 @spacedrone404 @entrider 

Rebased the repo, now I just need to make builds, but I am bogged down by making builds of Thorium. Builds should be out within the next couple of days.

In addition, going forward I will be providing SSE3 and AVX releases for both Linux and Windows. That way anyone can run it.

**Comment by sergeevabc** [comment]
@Alex313031, while we are waiting for the latest Mercury release, I am glad to inform you that the [recent Thorium](https://github.com/Alex313031/thorium-win7/releases/tag/M109.0.5414.173) x64 SSE3 works fine on my end, at last!

**Comment by andika207** [comment]
> [@Alex313031](https://github.com/Alex313031), Mercury v.115.4.0 does not work under Windows 7 x64 on my end because you compiled it with SSE4.1 as a strict requirement, whereas my Core 2 Duo supports SSE3 only. 
Please, do something about it, it's just a matter of setting a proper compilation switch.

Supermium was developed with old hardware in mind that don't understand SSE4.1 instructions
chrome 86 for WinXP is working pretty well so I guess the chrome 109 would be fine for the next coming years 
I can sleep well without the latest greatest chrome release.
