### ISSUE TITLE
Mercury flagged as virus

### ISSUE THREAD

**Issue by Jesu-dotcom** [Alex313031/Mercury#53]
I installed Mercury from the main repo. After launching it, I didn't have any issue immediately. After five minutes of using it, my antivirus started to flag it as a trojan:

Event: Object deleted
Application: Mercury
User: -----
User type: Initiator
Component: System Watcher
Result description: Deleted
Type: Trojan
Name: PDM:Trojan.Win32.Generic
Threat level: High
Object type: Process
Object path: C:\Program Files\Mercury
Object name: mercury.exe
MD5: -----

This has happened at least 4 times.

Why did it happen? Should I just add an expcecion to my antivirus or is there something that's not working properly with Mercury?

**Comment by Jesu-dotcom** [comment]
Btw, I noticed that it was addressed here https://github.com/Alex313031/Mercury/issues/39, but as I mentioned, I'm still experiencing this issue with the latest release.

**Comment by gz83** [comment]
Mercury does not use malicious code or bundle malicious components, please consider this a false alarm from your antivirus program and try to report the problem to your antivirus vendor (from the information you provided, it seems you are currently using Kaspersky?).

@Jesu-dotcom @Maki711

**Comment by skifli** [comment]
I use Kaspersky and it was not flagged.
