### ISSUE TITLE
Norton & Malwarebytes see v115.4.0 as virus laden

### ISSUE THREAD

**Issue by vmoutsop** [Alex313031/Mercury#54]
Installed 115.4.0 after I saw Chris Titus's video on Thorium. Norton & Malwarebytes went nuts during and after the install calling out (Norton) accessing protected files and (Malwarebytes) phishing and malware being blocked. Was not thrilled about that and uninstalled it.

**Comment by gz83** [comment]
Mercury does not use any malicious code or bundle any malicious components, so please consider it a false alarm by your antivirus program and try to report the problem to Norton.

@vmoutsop

**Comment by vmoutsop** [comment]
I never said that Mercury used malicious code, just that 2 different programs identified issues, if it were one, I would say Norton is being overprotective or something, but when 2 programs find issues, that's a little different.  

Do whatever you want, I won't be installing or using something that is identified as suspect, just because you say it's OK. I don't know you, why would I take your word?

@gz83

**Comment by gz83** [comment]
It is up to you to decide whether to use this software. I have never expressed any intention to interfere with your choice. Whether you use it or not has no impact on us.

@vmoutsop

**Comment by vmoutsop** [comment]
Is this how you treat all your potential users?  You don't like my legitimate feedback about what happened so you're closing the ticket and basically telling me to use something else.  Nice, real nice. Chris Titus is doing you a world of favors by promoting your software and this is the thanks you give the community?

@gz83

**Comment by gz83** [comment]
> Is this how you treat all your potential users? You don't like my legitimate feedback about what happened so you're closing the ticket and basically telling me to use something else. Nice, real nice. Chris Titus is doing you a world of favors by promoting your software and this is the thanks you give the community?
> 
> @gz83

The reason why I closed this issue does not mean that we refuse your feedback on this issue, but because there are already a large number of duplicate issues in the issue tracker. Please understand.

I have reported this issue to Alex and am in communication with him about this issue.

@vmoutsop
