### ISSUE TITLE
RPM builds

### ISSUE THREAD

**Issue by eturkes** [Alex313031/Mercury#55]
Probably a low priority ahead of other work on Mercury but it would be great to see RPM builds as you have for Thorium. Thanks for your great work, fantastic projects!

**Comment by CorneliusCornbread** [comment]
Or better yet, make a Flatpak so Mercury can run on every distribution without special pacakges

**Comment by gz83** [comment]
Thanks for the advice

@eturkes @CorneliusCornbread
