### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by Zerogaku** [Alex313031/Mercury#56]
Hi I would like to know which is the faster browser, thorium or mercury?

**Comment by gz83** [comment]
There is no comparison between the different browsers, so we recommend that you choose your favorite browser after using it yourself.

@Zerogaku

**Comment by Zerogaku** [comment]
thanks but then does that mean that they've never been benchmarked side by side or that the 2 browsers are so different that they can't be compared

**Comment by gz83** [comment]
The infrastructure, optimization parameters, and development technologies of the two browsers are different and cannot be compared well.

@Zerogaku

**Comment by Zerogaku** [comment]
that makes sense, thanks
