### ISSUE TITLE
NixOS Support

### ISSUE THREAD

**Issue by orxngc** [Alex313031/Mercury#57]
I use NixOS and can't use Mercury (or thorium.) It would be really nice to have it packaged as a nixpkg! I love mercury and I'm heartbroken that I can't use it here.

**Comment by gz83** [comment]
Thanks for the advice.

@sahmed011

**Comment by necrophcodr** [comment]
> I use NixOS and can't use Mercury (or thorium.) It would be really nice to have it packaged as a nixpkg! I love mercury and I'm heartbroken that I can't use it here.

You might get away with running it with the `steam-run` binary from the `steam` derivation, such as `steam-run path/to/mercury`.

Support for NixOS is already underway in the https://github.com/NixOS/nixpkgs/ repository, see issue https://github.com/NixOS/nixpkgs/issues/255399 for the request and the current derivation implementation underway here: https://github.com/NixOS/nixpkgs/pull/261805

**Comment by redxtech** [comment]
> I use NixOS and can't use Mercury (or thorium.) It would be really nice to have it packaged as a nixpkg! I love mercury and I'm heartbroken that I can't use it here.

I'm the one currently working on the PR to get mercury merged into `nixpkgs`, if you want I can lend a hand getting it working locally, at least until it gets merged.

You can pretty much just check the PR, and put the `package.nix` either in you system config or `home-manager`, and you add it to `systemPackages` or `userPackages` with a `callPackage` statement.

**Comment by sahmed011** [comment]
Okay, excited to hear that. I'll wait for it to get merged, thanks for the info!
