### ISSUE TITLE
New install Error upon finishing

### ISSUE THREAD

**Issue by xanaddams** [Alex313031/Mercury#58]
It still opened and ran, but the installer on windows gave this error after install.

Error opening file for writing:
C:\Users\ALEXAN~1.LAP\AppData\Local\Temp\nsdA6EA.tmp\modern
-wizard.bmp
Click Abort to stop the installation,
Retry to try again, or
Ignore to skip this file.

![error mercury](https://github.com/Alex313031/Mercury/assets/6765553/2c05ed28-0890-4139-bc8a-482e235482a6)

**Comment by gz83** [comment]
Check that you have sufficient permissions, or try installing Mercury somewhere other than the C drive.

@xanaddams
