### ISSUE TITLE
[Feature Request] Enable JXL support OOTB

### ISSUE THREAD

**Issue by louie-github** [Alex313031/Mercury#6]
As mentioned in the Release notes, JPEG XL (JXL) support was added via mozconfig and `--enable-jxl`. However, it isn't enabled out-of-the-box as of [release v.110.0a1](https://github.com/Alex313031/Mercury/releases/tag/v.110.0a1-1):

Going to https://jpegxl.info/test-page shows:
![image](https://user-images.githubusercontent.com/30176969/221399262-d8d408d2-796a-401c-bac2-14826ac8ca60.png)

As you can see, the JXL flag is not enabled by default:
![image](https://user-images.githubusercontent.com/30176969/221399283-63a874fb-6a79-45a1-8998-03b9d4ab6b05.png)

Enabling the flag manually allows the JXL images to appear as normal. I think you need to change the user preference by default as is done by Waterfox (see [000-waterfox.js](https://github.com/WaterfoxCo/Waterfox/blob/4e1dca751406fe4a71435f2088c9ac4eae7d41ad/waterfox/browser/app/profile/000-waterfox.js#L98))

On a related note, I think you might also want to disable the Nightly check for JXL support as done in this [Waterfox PR](https://github.com/WaterfoxCo/Waterfox/pull/2936/files), in case in the future you switch to building on Stable. I'd open a PR myself, but I'm not sure how to integrate it within your repository.

Thank you!

**Comment by gianni-rosato** [comment]
+1 for this! It's a delight to be able to use Thorium to view JXL images on the web, it'd be great to do the same with Mercury!

**Comment by BlueSwordM** [comment]
Yes, thank you!
Please merge all the patches, and the latest ones at that please :)

**Comment by goodusername123** [comment]
I would like to say that the default JXL support in firefox is very basic and is lacking support for transparency, animation, progressive decoding and color profiles however a pull request that was merged into waterfox adds support for all of these features and it should probably be merged into mercury as well and it can be found here https://github.com/WaterfoxCo/Waterfox/pull/2938
(patch file for just the improved JXL support is [here](https://github.com/WaterfoxCo/Waterfox/commit/771ed27676a39cb82deb2ed2548e9180415e815b.patch))

**Comment by gianni-rosato** [comment]
I think Mozilla refuses to because of their """neutral""" stance on JPEG-XL

**Comment by Alex313031** [comment]
@louie-github @gianni-rosato @BlueSwordM Done! > https://github.com/Alex313031/Mercury/commit/bd62664c0c84a861792c299a641b94d92f21e238 and https://github.com/Alex313031/Mercury/commit/c87b0271d587766a3780c2feb13673448ea5de75

**Comment by gianni-rosato** [comment]
You are a super developer! Your efforts are appreciated!!

**Comment by Alex313031** [comment]
@gz83 @BlueSwordM @louie-github @gianni-rosato New release, now with a windows installer. JXL enabled OOTB > https://github.com/Alex313031/Mercury/releases/tag/v.111.0.2

**Comment by goodusername123** [comment]
> > I would like to say that the default JXL support in firefox is very basic and is lacking support for transparency, animation, progressive decoding and color profiles however a pull request that was merged into waterfox adds support for all of these features and it should probably be merged into mercury as well and it can be found here [WaterfoxCo/Waterfox#2938](https://github.com/WaterfoxCo/Waterfox/pull/2938) (patch file for just the improved JXL support is [here](https://github.com/WaterfoxCo/Waterfox/commit/771ed27676a39cb82deb2ed2548e9180415e815b.patch))
> 
> @goodusername123
> 
> I have a better idea for this patch: why not just implement it upstream? Implementing it upstream will directly benefit the downstream derivatives. lol

@gz83 Mozilla refuses to review or implement these patches and they have been sitting around for over 2 years ignored and with the recent announcement that Mozilla is "neutral" on JPEG-XL it's very unlikely they will implement improved JPEG-XL support into the core of Firefox.

**Comment by gz83** [comment]
> > > I would like to say that the default JXL support in firefox is very basic and is lacking support for transparency, animation, progressive decoding and color profiles however a pull request that was merged into waterfox adds support for all of these features and it should probably be merged into mercury as well and it can be found here [WaterfoxCo/Waterfox#2938](https://github.com/WaterfoxCo/Waterfox/pull/2938) (patch file for just the improved JXL support is [here](https://github.com/WaterfoxCo/Waterfox/commit/771ed27676a39cb82deb2ed2548e9180415e815b.patch))
> > 
> > 
> > @goodusername123
> > I have a better idea for this patch: why not just implement it upstream? Implementing it upstream will directly benefit the downstream derivatives. lol
> 
> @gz83 Mozilla refuses to review or implement these patches and they have been sitting around for over 2 years ignored and with the recent announcement that Mozilla is "neutral" on JPEG-XL it's very unlikely they will implement improved JPEG-XL support into the core of Firefox.



> > > I would like to say that the default JXL support in firefox is very basic and is lacking support for transparency, animation, progressive decoding and color profiles however a pull request that was merged into waterfox adds support for all of these features and it should probably be merged into mercury as well and it can be found here [WaterfoxCo/Waterfox#2938](https://github.com/WaterfoxCo/Waterfox/pull/2938) (patch file for just the improved JXL support is [here](https://github.com/WaterfoxCo/Waterfox/commit/771ed27676a39cb82deb2ed2548e9180415e815b.patch))
> > 
> > 
> > @goodusername123
> > I have a better idea for this patch: why not just implement it upstream? Implementing it upstream will directly benefit the downstream derivatives. lol
> 
> @gz83 Mozilla refuses to review or implement these patches and they have been sitting around for over 2 years ignored and with the recent announcement that Mozilla is "neutral" on JPEG-XL it's very unlikely they will implement improved JPEG-XL support into the core of Firefox.

@goodusername123 

Has the recently released Mercury met your needs? If it hasn't met it, what haven't we done?

**Comment by goodusername123** [comment]
> > > > I would like to say that the default JXL support in firefox is very basic and is lacking support for transparency, animation, progressive decoding and color profiles however a pull request that was merged into waterfox adds support for all of these features and it should probably be merged into mercury as well and it can be found here [WaterfoxCo/Waterfox#2938](https://github.com/WaterfoxCo/Waterfox/pull/2938) (patch file for just the improved JXL support is [here](https://github.com/WaterfoxCo/Waterfox/commit/771ed27676a39cb82deb2ed2548e9180415e815b.patch))
> > > 
> > > 
> > > @goodusername123
> > > I have a better idea for this patch: why not just implement it upstream? Implementing it upstream will directly benefit the downstream derivatives. lol
> > 
> > 
> > @gz83 Mozilla refuses to review or implement these patches and they have been sitting around for over 2 years ignored and with the recent announcement that Mozilla is "neutral" on JPEG-XL it's very unlikely they will implement improved JPEG-XL support into the core of Firefox.
> 
> > > > I would like to say that the default JXL support in firefox is very basic and is lacking support for transparency, animation, progressive decoding and color profiles however a pull request that was merged into waterfox adds support for all of these features and it should probably be merged into mercury as well and it can be found here [WaterfoxCo/Waterfox#2938](https://github.com/WaterfoxCo/Waterfox/pull/2938) (patch file for just the improved JXL support is [here](https://github.com/WaterfoxCo/Waterfox/commit/771ed27676a39cb82deb2ed2548e9180415e815b.patch))
> > > 
> > > 
> > > @goodusername123
> > > I have a better idea for this patch: why not just implement it upstream? Implementing it upstream will directly benefit the downstream derivatives. lol
> > 
> > 
> > @gz83 Mozilla refuses to review or implement these patches and they have been sitting around for over 2 years ignored and with the recent announcement that Mozilla is "neutral" on JPEG-XL it's very unlikely they will implement improved JPEG-XL support into the core of Firefox.
> 
> @goodusername123
> 
> Has the recently released Mercury met your needs? If it hasn't met it, what haven't we done?

@gz83 

The current version of Mercury has issues with JXL images it's lacking proper support for transparency and color profiles and lacking any support for animation or progressive decoding, for example pages such as [this one](https://www.tentree.ca/pages/about) will have it's images only load in once they are 100% downloaded as opposed to being visible when only around 10% or 16% of them are done downloading which is really noticeable on slower network connections, the issues with animations and transparency can be seen on the JXL test page [here](https://jpegxl.info/test-page). all of these issues can be solved if the patch(es) I sent are merged into Mercury, they don't originate from the Waterfox project however the patch from Waterfox has all the code changes available as a single patch along with a single line changed to match up with more recent changes in the Firefox codebase.
