### ISSUE TITLE
OpenSuse (Tumbleweed) Support?

### ISSUE THREAD

**Issue by ElijahHW** [Alex313031/Mercury#60]
Hi there, came here from ChrisTitus shoutout. Just tried to install it from the .zip file. Extracted the files, and ran the terminal in the folder and ran `./run.sh`, but that results in this message.

```bash
~/Downloads/Mercury-v.115.4.0 took 2s 
❯ ./run.sh

Script to run Mercury in dev mode.

run.sh: line 42: cd: /root/mozilla-unified: No such file or directory
```

**Comment by allemand-instable** [comment]
You have to build it from source if I am not mistaken

There is a guide you can follow, you have to "bootstrap" the firefox source code on your machine at the locations specified for making the scripts work

**Comment by Alex313031** [comment]
@ElijahHW @allemand-instable Yeah, you can download the premade releases. I made Linux and Windows releases.

run.sh is only for running a debug build directly from the source code. Cloning and running that wont do anything. You have to run ./bootstrap.sh to download the firefox source, ./trunk.sh to check out the proper branch, ./setup.sh to copy Mercurys modified files over the source tree, ./build.sh to build it, and THEN you could use run.sh to run the build before running ./package.sh which generates release build installation packages,
