### ISSUE TITLE
Why does Mercury use on average 30% more RAM then Firefox?

### ISSUE THREAD

**Issue by Maki711** [Alex313031/Mercury#61]
In my testing where I would sync all my tabs and Addons from Firefox into Mercury 
and use both browsers at the same time and do same things, 
I noticed that on average Mercury would use around 30% more RAM then Firefox. Where Firefox would use 5GB Mercury would use 6GB or more.

Is there any explanation to this or is just my Hardware or Software?
Is there any way to more precisely test this?

I have AMD 7800x3d with 64GB (2x32GB Kit) DDR5 RAM from Corsair on Windows 10 22H2 (Build 19045.3570)

**Comment by gz83** [comment]
On what system are you using Mercury? Also, could you please specify what the browser is doing when this problem occurs?

@Maki711
