### ISSUE TITLE
[Feature Request] Native Titlebar Patch

### ISSUE THREAD

**Issue by Jevil7452** [Alex313031/Mercury#62]
In case you might not be aware, there exists a patch for Firefox: https://github.com/ephemeralViolette/firefox-native-controls that replaces the Windows 10-style titlebar (that looks out of place on Windows 7) with a titlebar that is drawn by the OS, so it will always look correct regardless of the theme the user is using. As this is a source code patch, it seems like a good idea to integrate it into the browser, so the users of this browser can enjoy having it be built-in, and not having to replace xul.dll files which will break when Firefox updates, unless the original author of the patch updates it too.

**Comment by MasterSlenderTR** [comment]
Yes, please, as a Win7 user I'd like to have this in Mercury.

**Comment by ephemeralViolette** [comment]
This doesn't currently handle the titlebar (only scrollbars), but it's designed for only ESR 115, which still supports the native Windows 7 titlebar.

**Comment by Alex313031** [comment]
@ephemeralViolette @MasterSlenderTR @Jevil7452 I will be adding this to the Mercury-Win7 repo.

For this repo, gonna leave it as is.
