### ISSUE TITLE
“Open application menu” keep selected after installiing an add-on

### ISSUE THREAD

**Issue by GrimPixel** [Alex313031/Mercury#64]
I just installed an add-on by clicking on “Add”. Then the “Open application menu” icon becomes active. I have to double-click on it to deactivate it.
To be precise, the prompt of confirmation doesn't show up.

**Comment by gz83** [comment]
Is this also the case on Firefox 115?

**Comment by GrimPixel** [comment]
I tried to reproduce, but the problem is gone.
