### ISSUE TITLE
Feature of opening the preference of an add-on easily

### ISSUE THREAD

**Issue by GrimPixel** [Alex313031/Mercury#65]
To open the preference of an add-on, steps requires are 
1. click on “Extensions”
2. click on the gear
3. click on “Manage Extension”
4. click on three dots
5. click on “Preferences

I think it can be improved by showing “Preferences” alongside the gear

**Comment by gz83** [comment]
thanks for the advice

**Comment by GrimPixel** [comment]
I think “Preferences” can be added to the right-click menu.
There is a use case: https://github.com/geajack/Wordology, where the user needs to open the preferences to manage the words to be highlighted. The add-on is usually pinned on the toolbar and requires a right-click and a left-click on “Options” on Thorium. I wish it could be as simple as that on Mercury.
