### ISSUE TITLE
Add-ons disappear after changing directory

### ISSUE THREAD

**Issue by GrimPixel** [Alex313031/Mercury#66]
Add-ons all disappeared after changing directory, after opening `mercury/mercury'.

The version is mercury_115.4.0_linux_x64.zip

**Comment by gz83** [comment]
Please try to refer to the following guide to modify the user data folder and see if you can recover the user data.

https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

**Comment by GrimPixel** [comment]
Yes. The problem was about different profiles. Thanks.
