### ISSUE TITLE
very slow performance

### ISSUE THREAD

**Issue by G2G2G2G** [Alex313031/Mercury#7]
Mercury gets 16.7 on https://browserbench.org/Speedometer2.1/
firefox gets 204
thorium avx gets 246
throium avx2 gets 218
edge gets 212

it's noticeable in regular browsing which is why I went to benchmark everything... and then saw it must be some bug?

**Comment by Alex313031** [comment]
@G2G2G2G Yeah I noticed that. I might make a disclaimer or set the latest release as a pre release. There is definitely something wrong with the javascript engine. This is not just mercury, this is a firefox 112 issue. 

Also, thats interesting that AVX2 thorium scored lower.
Can you tell me what system you have, and what CPU you have.

**Comment by G2G2G2G** [comment]
This was on Ryzen 3600X (with PBO and whatever else on)
Windows 10 with various things running in background but all the desktop stuff closed off, didn't really go hardcore into benchmarking and kill off a bunch of stuff. Was just a quick curiosity test.


I have an office we have many of the same CPUs but have:
```
Intel i7-5820K (only linux, headless email server so can't really test)

Ryzen 3700X (only linux)
Ryzen 3600X
Ryzen 3600G (I think, I'd have to double check that one which integrated gpu version it is)

Ryzen 2700
Ryzen 2600X
Ryzen 2600
```
and some various others for laptops. 

I remember some AVX memes for ryzen so not sure which got meme'd by the "half support of AVX" or whatever they were years ago... not sure if that is why AVX2 does worse?

I noticed though on thorium avx2 version that several sites break so I assume some broken stuff could lag tests and completely break others (jet whatever stream didn't work, already some git issues on that elsewhere)

Also looking at edge and seeing the posts about it over the months with how much faster people see it is vs chrome.. I am starting to think maybe microsoft builds it with AVX for systems that support it as they have the underlying OS data before even sending the browser to the computer vs chrome which just has a download link and no other control over the OS? Or am I completely wrong? I assume there's a way to detect whether or not something is.

(also if you don't want to go of ftopic in this thread want to go further in the discussion I can email your email or whatever if you want. but I don't care if you don't!)
