### ISSUE TITLE
Mercury 0xc0000142 Error When Installing

### ISSUE THREAD

**Issue by Meolsei** [Alex313031/Mercury#74]
Multiple versions that I have tried to install would not install _correctly_ and would instead give me the error stated in the title. It does finish the installation, but the main app would do the same thing anyway.

OS: Windows 10 2016 LTSB (x64)
Ver: 115.4.0

**Comment by gz83** [comment]
What processor is your computer using?

**Comment by Meolsei** [comment]
Well, considering the laptop's age, it's using a Pentium N3700. I don't use it too often, but it runs.

**Comment by Meolsei** [comment]
> Well, considering the laptop's age, it's using a Pentium N3700. I don't use it too often, but it runs.

I only really use it when I wanna just watch something in bed.

**Comment by gz83** [comment]
I think it may be because the instruction set does not support it. I am not sure whether Mercury also provides SSE3/SSE4 versions like Thorium.

**Comment by Meolsei** [comment]
Well, thanks for helping out anyway. At least I can still use Thorium.
