### ISSUE TITLE
permission pop up flickering

### ISSUE THREAD

**Issue by babylaaamp** [Alex313031/Mercury#75]
Not every permission popup but this one when I want to call messenger it keeps flickering
https://github.com/Alex313031/Mercury/assets/64625924/4ad6c0db-9bba-456a-b7d9-5c30c1008c37

**Comment by gz83** [comment]
Does the same version of Firefox also have this problem? Personally I think the focus was not captured correctly.

**Comment by babylaaamp** [comment]
No I think, I just switched from Librewolf and it doesn't have this problem

**Comment by gz83** [comment]
Please backup the current user data, then open Mercury using a new user data folder, and check again to see if the problem continues to occur.
