### ISSUE TITLE
Clarify if Betterfox is implemented

### ISSUE THREAD

**Issue by sycam0r-e** [Alex313031/Mercury#76]
In issue https://github.com/Alex313031/Mercury/issues/38 it sounds like you added [Betterfox](https://github.com/yokoffing/Betterfox) from v.115.3.0 onwards. However, Betterfox is not mentioned in your [PATCHES.md](https://github.com/Alex313031/Mercury/blob/main/docs/PATCHES.md) or in the top-level README. This issue is to clarify whether you include Betterfox and if so suggests to add it to the PATCHES, README, and repo's about section.

**Comment by gz83** [comment]
Thanks for pointing this out

**Comment by Alex313031** [comment]
@gz83 @sycam0r-e Good idea, I will update those files. Note that I didn't include the entire betterfox.js, only the settings related to performance.

**Comment by Alex313031** [comment]
@sycam0r-e Done! > https://github.com/Alex313031/Mercury/commit/98f709407572a5c1aacfd3b973f5f67b5e946ba3

**Comment by sycam0r-e** [comment]
nvmnd will never use anything from here

https://github.com/Alex313031/Mercury/issues/115
