### ISSUE TITLE
Diff inclusion

### ISSUE THREAD

**Issue by Steven11q** [Alex313031/Mercury#77]
This is more of a feature request, but once youve taken all the tweaks your planning on adding, could you make a .diff file so that its easier for other people to apply these patches to source code on their own? 
I personally would like to take all the compiler optimizations etc and apply them to waterfox/floorp. 
Thank you.

**Comment by gz83** [comment]
Most of the changes can be seen in the PATCHES.md file, but this document may need further updating at this time.

https://github.com/Alex313031/Mercury/blob/main/docs/PATCHES.md

In addition, compilation optimization parameters are passed through mozconfigure

https://github.com/Alex313031/Mercury/tree/main/mozconfigs

**Comment by Alex313031** [comment]
@Steven11q @gz83 This is a good idea though, for both Thorium and Mercury. It is easy to do. Just `git diff >> /path/to/file.patch` and then one could run `git apply --reject /path/to/file.patch`

I will make sure to put a .patch file in the releases going forward. If I happen to forget next release, PLEASE ping me here and remind my forgetful ass lol.
