### ISSUE TITLE
Cannot use Spotify on mercury.

### ISSUE THREAD

**Issue by Estebiu** [Alex313031/Mercury#78]
DRM playback doesn't seem to be working; 
![image](https://github.com/Alex313031/Mercury/assets/61051731/a2b216d2-c6de-4af5-a86c-bd22c0303af7)
This is the message that appears.

Any guesses? Drm playback is activated in mercury's settings.

**Comment by gz83** [comment]
This is probably in line with Thorium's inability to play certain audio and video processed by widevine, and I think Mercury would likewise need to purchase a widevine key in order to make widevine work at all, but unfortunately we can't do that at the moment

**Comment by Chaython** [comment]
> DRM playback doesn't seem to be working; ![image](https://private-user-images.githubusercontent.com/61051731/282428888-a2b216d2-c6de-4af5-a86c-bd22c0303af7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjcxNTIsIm5iZiI6MTcwMjU2Njg1MiwicGF0aCI6Ii82MTA1MTczMS8yODI0Mjg4ODgtYTJiMjE2ZDItYzZkZS00YWY1LWE4NmMtYmQyMmMwMzAzYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE1MTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YzRiMjQzZWVhZmM3OGYzNTFlNmM2NWMzMjk4MTc0NDYzMGQ3MzBiMDljMTJjMTFjMzZiMjYwOGNlNDQwOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aj6aWJ6WMY7o9vxRWI5cagQc8cAaJunGCJHblwA6xkE) This is the message that appears.
> 
> Any guesses? Drm playback is activated in mercury's settings.

This issue exists on all non-mozilla firefox forks
