### ISSUE TITLE
Sign in asks for email, not for pass, goes "Working" for more than an hour

### ISSUE THREAD

**Issue by cg00001** [Alex313031/Mercury#8]
Maybe it's because I had Pulse -Firefox fork- installed and it left something in one of the folders, even after uninstalling it?
![Mercury Sign In](https://user-images.githubusercontent.com/38960370/226931883-f172d4ba-39d9-4b12-b790-c945e03c14f4.jpg)

**Comment by cg00001** [comment]
Forgot to mention that I've been using Thorium without a single glitch since almost it came out, so I don't think this has something to do with my desktop specs.

**Comment by Neucher** [comment]
I have this same issue. New profile

**Comment by Cir-0** [comment]
I am also having this issue on Arch Linux, using the mercury-browser-bin package from the AUR (Mercury version 112.0.3).

**Comment by cg00001** [comment]
> I am also having this issue on Arch Linux, using the mercury-browser-bin package from the AUR (Mercury version 112.0.3).
> 
> EDIT: I appear to have found a workaround:
> 
> 1. Open Mercury Browser at least once so it auto-generates the profiles. Then close Mercury Browser.
> 2. Open Firefox or Waterfox and sign in to Firefox Sync.
> 3. Go into the auto-generated Mercury profile (on linux, in ".mercury" in the home folder, go into the folder that contains more than just a "times.json" file) and delete everything in it.
> 4. Copy the contents of the Firefox/Waterfox profile (on linux, in the .mozilla or .waterfox folder in the home folder, go into the profile folder that contains more than just a "times.json" file) and copy all of the contents into the Mercury profile folder.
> 5. Open Mercury Browser, it should launch with the profile logged into Firefox sync.

Workaround works nicely.

**Comment by cg00001** [comment]
> I am also having this issue on Arch Linux, using the mercury-browser-bin package from the AUR (Mercury version 112.0.3).
> 
> EDIT: I appear to have found a workaround:
.......

It seems the workaround doesn't work around anymore, lol.

**Comment by cg00001** [comment]
Just made a shortcut to https://github.com/issues and found out I had forgotten this issue open, it has been fixed since several Mercury versions ago.
Here are some bonus Mercury Arch themes of mine for those reading this, lol.
https://addons.mozilla.org/en-US/firefox/user/14243925/
