### ISSUE TITLE
macOS builds?

### ISSUE THREAD

**Issue by future10se** [Alex313031/Mercury#9]
Thank you for developing Thorium and Mercury.

Would you consider maintaining a macOS build for Mercury as well?

**Comment by Alex313031** [comment]
@Midzer makes the macos thorium builds because you need a mac to compile, which I don't have. It would be up to him.

**Comment by surapunoyousei** [comment]
I recommend to use GitHub Actions.

**Comment by gz83** [comment]
I don't agree with using GitHub Actions, it doesn't bring much convenience

@surapunoyousei

**Comment by surapunoyousei** [comment]
It is up to the developer to decide, but we are saying that if the focus is on providing the product, it should be used.

Not convenient, but practical.

**Comment by gz83** [comment]
Mercury is a relatively large project. If we use GitHub Action to compile and publish, we need to create multiple different bots, and the entire compilation process takes a long time, and operations such as modifying code are not as convenient as compiling on a local device.

In addition, GitHub Action has certain restrictions, and it is not a free product.

The above is my opinion, we also need to listen to the opinions of other team members.

@surapunoyousei

**Comment by surapunoyousei** [comment]
@gz83 Not to be contrary, but Github Actions does not charge for public repositories. It is completely free.

We also use it to build our Floorp. The beta version is built on a Github Actions machine, but the stable version is built using Buildjet.

1400行ぐらいを書かなければ自動化できませんが、行った後は非常に便利です。

https://github.com/Floorp-Projects/Floorp/actions/runs/5498342219

https://github.com/Floorp-Projects/Floorp/actions/runs/5498342219/workflow

I think it is worth doing, but there is certainly no problem at all doing it locally.

**Comment by gz83** [comment]
Thank you for providing more information

+Alex
+midzer

@Alex313031 @midzer

**Comment by allemand-instable** [comment]
I tried to build the binaries from source on my M1 mac but I get the following error :

```
 0:00.41 checking for vcs source checkout... hg
 0:00.41 checking for a shell... /bin/sh
 0:00.43 checking for host system type... aarch64-apple-darwin23.1.0
 0:00.44 checking for target system type... x86_64-pc-linux-gnu
 0:00.46 Traceback (most recent call last):
 0:00.46   File "/Users/allemandinstable/mozilla-unified/configure.py", line 351, in <module>
 0:00.46     sys.exit(main(sys.argv))
 0:00.46              ^^^^^^^^^^^^^^
 0:00.46   File "/Users/allemandinstable/mozilla-unified/configure.py", line 138, in main
 0:00.46     sandbox.include_file(os.path.join(os.path.dirname(__file__), "moz.configure"))
 0:00.46   File "/Users/allemandinstable/mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 494, in include_file
 0:00.46     exec_(code, self)
 0:00.46   File "/Users/allemandinstable/mozilla-unified/python/mozbuild/mozbuild/util.py", line 56, in exec_
 0:00.46     exec(object, globals, locals)
 0:00.46   File "/Users/allemandinstable/mozilla-unified/moz.configure", line 209, in <module>
 0:00.46     include("build/moz.configure/memory.configure", when="--enable-compile-environment")
 0:00.46   File "/Users/allemandinstable/mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 868, in include_impl
 0:00.46     self.include_file(what)
 0:00.46   File "/Users/allemandinstable/mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 494, in include_file
 0:00.46     exec_(code, self)
 0:00.47   File "/Users/allemandinstable/mozilla-unified/python/mozbuild/mozbuild/util.py", line 56, in exec_
 0:00.47     exec(object, globals, locals)
 0:00.47   File "/Users/allemandinstable/mozilla-unified/build/moz.configure/memory.configure", line 95, in <module>
 0:00.47     @depends("--enable-phc", target, have_unwind, when="--enable-jemalloc")
 0:00.47                                      ^^^^^^^^^^^
 0:00.47 NameError: name 'have_unwind' is not defined
```

### what I have done before 

```zsh
 7356  mv Mercury-v.115.4.0 $HOME/Mercury
 7359  cd $HOME/Mercury/
 7362  chmod +x bootstrap.sh
 7367  conda install mercurial
 7368  sudo ./bootstrap.sh
 7371  sudo ./setup.sh
 7374  sudo ./build.sh
```

Mozilla bootstrap

- refused telemetry
- downloaded artifacts firefox source build ( default )

Let me know if you think of any relevant information you would like to know

**Comment by gz83** [comment]
It seems that the compilation parameters you used are incorrect, and we currently do not seem to provide compilation parameters for MacOS. I will now forward this issue to Alex and midzer for further investigation.

@Alex313031 @midzer
