### ISSUE TITLE
bookmark toolbar icons stuck

### ISSUE THREAD

**Issue by fijibestwater** [Alex313031/Mercury#90]
I signed into mercury with my firefox account and it seems to have imported all of my bookmarks however none of them have their custom icons. 
<img width="1300" alt="explorer_s2VIk2YjRZ" src="https://github.com/Alex313031/Mercury/assets/152419829/630aa29e-748d-4fb4-929b-ceee40fb3bf9">

**Comment by Alex313031** [comment]
@retardedboy I've had this happen too, with vanilla firefox as well. Mercury changes no code at all relating to bookmarks, so I think this is an upstream thing.
