### ISSUE TITLE
121 Windows 7 support

### ISSUE THREAD

**Issue by K4sum1** [Alex313031/Mercury#92]
I have been working on this for a bit. It's not perfect, but it gets Firefox 121 working on Windows 7.
https://github.com/Eclipse-Community/vyvfox

The only real issue is this, which maybe you could help me fix or I could get it figured out and fixed myself.
https://github.com/Eclipse-Community/vyvfox/issues/4

Also if you don't want to use my code, at least add 8 compatibility. It just works as is.

**Comment by Alex313031** [comment]
@K4sum1 How can I add 8 compatibility. Also, I would use your code if you synced it to stable, not tip of tree. I.E. mozilla-release rather than mozilla-central (these are the tags when using HG, but of course your fork is using Git)

**Comment by K4sum1** [comment]
> @K4sum1 How can I add 8 compatibility. Also, I would use your code if you synced it to stable, not tip of tree. I.E. mozilla-release rather than mozilla-central (these are the tags when using HG, but of course your fork is using Git)

I am using the release branch of gecko-dev, or https://github.com/mozilla/gecko-dev/tree/release
If you want me to move to something else I can just rebase or even do the commits on your repo. 122 is being a bish so I kinda want to restart anyways since I have no idea how to debug Firefox build errors.

For 8, the absolute minimum would be doing something like this,
https://github.com/Eclipse-Community/vyvfox/commit/8dcd8cd484ae5d7ca1c5c0e16ffeb843dcc90079

However also this is pretty basic and would help too.
https://github.com/Eclipse-Community/vyvfox/commit/cfb1c3f31d1509635493848ab4e4eb5c9a3b08b4

Only real issue is that the window border is the 10 one, but it runs well enough. I'm not sure when or if I will get that reverted in my fork.

**Comment by Alex313031** [comment]
Noice!
I will try to make a build based on this. Im gonna set the minimum version and subsystem to NT 6.0 though

**Comment by Alex313031** [comment]
@K4sum1 DID IT!

Mercury 121.0.1 for Windows 7/8/8.1! >https://github.com/Alex313031/Mercury-Win7/releases/tag/121beta

**Comment by K4sum1** [comment]
> @K4sum1 DID IT!
> 
> Mercury 121.0.1 for Windows 7/8/8.1! >https://github.com/Alex313031/Mercury-Win7/releases/tag/121beta

Do you have somewhere I can communicate to you about browser and other development? Somewhere more private than GitHub? Discord could work unless you want me to use something else.

**Comment by Alex313031** [comment]
@K4sum1 Ooof anything besides discord. My least favourite electron app lol.

**Comment by K4sum1** [comment]
> @K4sum1 Ooof anything besides discord. My least favourite electron app lol.

You could use it in browser, use the Supermium Electron ArmCord mod, Ripcord, Gtkcord4, whatever else exists.

> Also, I have some suggestions for you for your repo, and also to tell you that the latest commit "branding part 2" you accidently set exec permissions on all the files. This can happen when you push from windows.

Not really sure what that means. I think I did branding part 2 when my Windows 10 install on my compiling VM fucked itself and I had to quickly configure the admin account to push branding changes I had been waiting to publish. Would like these suggestions, or maybe even just merging idk.

**Comment by Alex313031** [comment]
@K4sum1 LOL I actually have a fork of armcord for windows 7. I will install it and use it to message u. I totally forgot about it. I hate the official discord app. The web app is OK.

**Comment by Alex313031** [comment]
@K4sum1 Is your discord handle the same name?

**Comment by K4sum1** [comment]
> @K4sum1 Is your discord handle the same name?

Yes

**Comment by K4sum1** [comment]
> @K4sum1 LOL I actually have a fork of armcord for windows 7. I will install it and use it to message u. I totally forgot about it. I hate the official discord app. The web app is OK.

@Alex313031 You don't seem to be very active on Discord. You got something else I can use that you check more often? I can use Matrix, but I don't like it. Email could work. I don't know anything else I really use.

**Comment by Alex313031** [comment]
@K4sum1 You dont use facebook messenger?

And its because I hate leaving an electron app running all the time. Its bad enough on windows 11 with webview2 always running.

**Comment by K4sum1** [comment]
> @K4sum1 You dont use facebook messenger?

No Facebook account at all. All I really have are Discord, Matrix, and email. I might have an old IRC thing somewhere, but I can't be bothered to dig it out.

**Comment by K4sum1** [comment]
@Alex313031 Any other method?

**Comment by K4sum1** [comment]
@Alex313031 I tried pinging you elsewhere, but you didn't check. I have a question about mozconfigs on Discord.

**Comment by K4sum1** [comment]
@Alex313031 I have a Telegram account now, I saw you in search, but it says you were last active in 2023. I've been porting Firefox 123 finally, but I have a weird crashing issue under 7, and I might need your help.
