### ISSUE TITLE
Waiting for v.121.0.1 for windows

### ISSUE THREAD

**Issue by choicky** [Alex313031/Mercury#94]
Thank you very much

**Comment by jestxfot** [comment]
Am I correct in assuming it's not out yet?

**Comment by Alex313031** [comment]
@choicky @jestxfot I had a machine issue, but my machine is back up. However, right now I am working on Thorium for Windows 7. I will build the Mercury releases tommorow.

**Comment by tr1xem** [comment]
same here

**Comment by tr1xem** [comment]
day 3

**Comment by Alex313031** [comment]
@choicky @jestxfot @tr1xem https://github.com/Alex313031/Mercury/releases/tag/v.121.0.2 Here you go.

**Comment by tr1xem** [comment]
> @choicky @jestxfot @tr1xem https://github.com/Alex313031/Mercury/releases/tag/v.121.0.2 Here you go.
> 
> LOL
> 
> ![image](https://private-user-images.githubusercontent.com/45863095/295474845-3757c68b-d97e-4de2-9366-a97596fcbb9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzk5NDksIm5iZiI6MTcwNDg3OTY0OSwicGF0aCI6Ii80NTg2MzA5NS8yOTU0NzQ4NDUtMzc1N2M2OGItZDk3ZS00ZGUyLTkzNjYtYTk3NTk2ZmNiYjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA5NDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OTUwM2I5ZjBhZTY2MWIxNzY5MGJjOGU4OGQ1ZmFjNDg0MDI5MjdkMTQzNjIxMzJhZmMyMmMyZjI3ZjQ2YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nrb0vmoo9BR1MXioWBEh1CqanLOv83cHg4nJ85tv1RU)

lol ty :3 u awesome

**Comment by choicky** [comment]
> @choicky @jestxfot @tr1xem https://github.com/Alex313031/Mercury/releases/tag/v.121.0.2 Here you go.
> 
> LOL
> 
> ![image](https://private-user-images.githubusercontent.com/45863095/295474845-3757c68b-d97e-4de2-9366-a97596fcbb9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTcxMjIsIm5iZiI6MTcwNDg5NjgyMiwicGF0aCI6Ii80NTg2MzA5NS8yOTU0NzQ4NDUtMzc1N2M2OGItZDk3ZS00ZGUyLTkzNjYtYTk3NTk2ZmNiYjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE0MjcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlODA3Zjk2MzAzZmU4YmUzYzJiMGRlNzUwM2U2OWFlMWU3Njk4MzNkOWZiY2Q1MzEwZTY4ZjIwM2M0Y2U4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9vnPsn92JLD1eFgXKhpIsk8NEFSL107S8d9hNy0ioHQ)


Thank you very much for your hardwork.

I've download and installed to my Thinkbook 14+ runing  Windows 11 on AMD 7840H.

According to https://web.basemark.com/ , Mercury is faster than firefox by 7%~15%.  However, It's substantially same performance according to https://browserbench.org/ , sometime slower by 1%~2%, intersting.  Just FYI.
