### ISSUE TITLE
Suggestion: To add proton ui as default or as a option to switch

### ISSUE THREAD

**Issue by tr1xem** [Alex313031/Mercury#96]
![image](https://github.com/Alex313031/Mercury/assets/100174637/e084fa16-5cf8-42c0-b588-a66c307adfe0)

As It looks better than current firefox ui . current ui is bit old dated in my pov
If not u can make a mercury theme of it 

Source : 
https://github.com/black7375/Firefox-UI-Fix

**Comment by jestxfot** [comment]
I don't think the browser should add any css changes to its code, it will load the computers. Ready-made add-ons already exist, and it's not that hard to add them to any browser by yourself

**Comment by tr1xem** [comment]
> I don't think the browser should add any css changes to its code, it will load the computers. Ready-made add-ons already exist, and it's not that hard to add them to any browser by yourself

but its a patch from waterfox and ig it enhances looks so why not a new feature
